Topic 0 and 1
jdavisonc/java-bootcamp pull request #9
Opened 2018-09-23 20:14 UTC by mathiastecho

2018-09-26 14:48 UTC, jdavisonc requested changes
For some reason I see a lot of hidden file on the PR, would you like to review the .ignore file and make sure that eclipse private files are not added to the PR?
Thanks!

2018-10-01 06:42 UTC, mathiastecho commented
@jdavisonc deleted the old folder with the hidden files and also pushed the files for topic 2 and 3. PTAL

2018-10-01 13:04 UTC, jdavisonc reviewed
Some minor comments

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic1/topic1.3/src/test/java/com/mathiastechera/app/AppTest.java
> +    extends TestCase
Instead of use TestCase you can just annotatio the test with `@Test` and also use `@Before` or `@After`

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestCartService.java
> +		assertTrue(!apple.equals(orange) );
You can use `assertFalse()`

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestCartService.java
> +		assertTrue(cart.getAmountOfDifferentItems() == 3 && cart.getAmountOfItems() == 4);
Maybe would be better to split in two asserts?

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestCartService.java
> +		assertTrue(cart.getAmountOfDifferentItems() == 1 && cart.getAmountOfItems() == 1);
Maybe would be better to split in two asserts?

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestUserService.java
> +		assertTrue(result1 && !result2);
Maybe would be better to split in two asserts?

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestUserService.java
> +		assertTrue(result && userService.getUserDB().size() == amountOfUsersExpected);
Maybe would be better to split in two asserts?

2018-10-01 13:04 UTC, jdavisonc commented on mathias_techera/topic2/topic2/src/test/java/topic2/TestUserService.java
> +public class TestUserService {
Nice tests! :100:

2018-10-02 21:47 UTC, mathiastecho commented
I implemented the recommendations. PTAL

2018-10-03 14:30 UTC, jdavisonc approved these changes
Looks good to me

2018-10-08 20:58 UTC, jdavisonc approved these changes

2018-10-08 20:58 UTC, merged